import * as types from 'actions/ActionTypes';

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const PREFERENCE_POST = "PREFERENCE_POST";
export const PREFERENCE_POST_SUCCESS = "PREFERENCE_POST_SUCCESS";
export const PREFERENCE_POST_FAILURE = "PREFERENCE_POST_FAILURE";

export const PREFERENCE_GET = "PREFERENCE_GET";
export const PREFERENCE_GET_SUCCESS = "PREFERENCE_GET_SUCCESS";
export const PREFERENCE_GET_FAILURE = "PREFERENCE_GET_FAILURE";

export const PREFERENCE_REMOVE = "PREFERENCE_REMOVE";
export const PREFERENCE_REMOVE_SUCCESS = "PREFERENCE_REMOVE_SUCCESS";
export const PREFERENCE_REMOVE_FAILURE = "PREFERENCE_REMOVE_FAILURE";

export const PREFERENCE_EDIT = "PREFERENCE_EDIT";
export const PREFERENCE_EDIT_SUCCESS = "PREFERENCE_EDIT_SUCCESS";
export const PREFERENCE_EDIT_FAILURE = "PREFERENCE_EDIT_FAILURE";